<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\TradeFlow.Api\TradeFlow.Api.csproj" />
    <ProjectReference Include="..\..\src\TradeFlow.Infrastructure\TradeFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
